SET NAMES utf8; SET FOREIGN_KEY_CHECKS=0;
CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  dni VARCHAR(20) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('admin','supervisor','vendedor','stock','caja') NOT NULL DEFAULT 'admin',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS societies (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  tax_id VARCHAR(20) NULL,
  email VARCHAR(120) NULL,
  phone VARCHAR(60) NULL,
  address VARCHAR(160) NULL,
  city VARCHAR(80) NULL,
  state VARCHAR(80) NULL,
  postal_code VARCHAR(15) NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS branches (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  society_id INT UNSIGNED NOT NULL,
  name VARCHAR(120) NOT NULL,
  address VARCHAR(160) NULL, city VARCHAR(80) NULL, state VARCHAR(80) NULL, postal_code VARCHAR(15) NULL,
  manager VARCHAR(120) NULL, is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_br_soc (society_id),
  CONSTRAINT fk_br_soc FOREIGN KEY (society_id) REFERENCES societies(id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- admin seed (dni 00000000 / pass admin123)
INSERT INTO users (dni,name,password_hash,role,is_active)
SELECT '00000000','Administrador','$2y$10$N0Q.8n0pVToSx4eYjW3V0e0x0t8m8n5xg7z0sQw1C9z1y2X3Z4Y2K','admin',1
WHERE NOT EXISTS(SELECT 1 FROM users WHERE dni='00000000');
SET FOREIGN_KEY_CHECKS=1;